<?php
/**
 * Generated by framework installer - Mon, 14 Dec 2015 21:07:59 +0100
*/
    class Config
    {
	const BASEDNAME	= '/csc3123';
	const DBHOST	= 'localhost';
	const DB	= 'csc3123';
	const DBUSER	= 'csc3123';
	const DBPW	= 'csc3123';
	const SITENAME	= 'csc3123';
	const SITEURL	= 'http://milton.com';
	const SITENOREPLY	= 'noreplay@milton.com';
	const SYSADMIN	= 'm.li24@ncl.ac.uk';
    }
?>